# Generated by Django 4.2 on 2025-01-31 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_length', models.PositiveIntegerField(help_text='Length of menstrual cycle in days')),
                ('last_period_date', models.DateField()),
                ('tracking_date', models.DateField(auto_now_add=True)),
                ('cramps', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('irritable', 'Irritable'), ('anxious', 'Anxious'), ('sad', 'Sad')], max_length=10)),
                ('did_train', models.BooleanField(default=False)),
                ('performance_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
